# Generated by Django 2.1.3 on 2018-11-27 10:21

from django.db import migrations, models
from badger.models import Employee

def migrate_data_forward(apps, schema_editor):
    for instance in Employee.objects.all():
        print("Generating slug for {}".format(instance))
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('badger', '0002_badge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
	migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
