# Generated by Django 2.1.3 on 2018-11-28 09:44

from django.db import migrations, models
from badger.models import Badge

def migrate_data_forward(apps, schema_editor):
    for instance in Badge.objects.all():
        print("Generating slug for {}".format(instance))
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0003_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
	migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
