# Generated by Django 2.1.3 on 2018-12-03 14:06

import badger.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0004_add_slug_to_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=30, validators=[badger.validators.validate_employee_name]),
        ),
    ]
