# Generated by Django 2.1.3 on 2018-12-03 14:17

import badger.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0005_first_name_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=30, validators=[badger.validators.validate_employee_name]),
        ),
    ]
