# Generated by Django 2.1.3 on 2018-12-08 13:16

from django.db import migrations, models
from badger.models import Employee

def migrate_data_forward(apps, schema_editor):
    for instance in Employee.objects.all():
        print("Generating slug for {}".format(instance.slug))
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0006_last_name_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward)
    ]
