# Generated by Django 2.1.3 on 2018-12-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0009_badgeawarded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgeawarded',
            options={'verbose_name_plural': 'BadgesAwarded'},
        ),
    ]
