# Generated by Django 2.1.3 on 2018-12-25 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0010_auto_20181220_1501'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='badgeawarded',
            managers=[
                ('user_badges', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='badgeawarded',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges_awarded', to=settings.AUTH_USER_MODEL),
        ),
    ]
