# Generated by Django 2.1.3 on 2019-01-04 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badger', '0011_auto_20181225_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badgeawarded',
            unique_together={('user', 'badge')},
        ),
    ]
