# Generated by Django 2.1.3 on 2019-01-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badger', '0012_user_badge_once'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='badgeawarded',
            managers=[
            ],
        ),
    ]
